### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by Onair-santa** [Netrvin/telegram-pm-chat-bot#6]
command /Info
I need full info about Sender
1 Full Name
2 ID 99999999
3 Uname   @Sender

And now 
Sender: Firstname Link

What is Link? Where is info about sender?
And need markdown in start text. And full info in first msg.
Thnx

**Comment by Onair-santa** [comment]
![image](https://user-images.githubusercontent.com/42511409/231427723-67899655-33b4-4d6f-b103-12e7ca8042c8.png)

**Comment by Onair-santa** [comment]
Bot is good and work fine.
But i have 500 clients and 100 with identical Name.
And need not only text in start.
And need other lng. file editing does not work in other languages, and we have bugs

**Comment by Debcharon** [comment]
https://github.com/Netrvin/telegram-pm-chat-bot/blob/34477529b09c691fe5652ad6fa3470ef2abb6f05/lang/en.json#L7

When "Who can add a link to my account when forwarding my messages" is set to nobody, the link will be not added (Privacy and Security -> Forwarded Messages).

![image](https://user-images.githubusercontent.com/107681877/231687153-1179c4da-b059-41e1-9306-30ff21e9cc24.png)

**Comment by Onair-santa** [comment]
Here is how it was done in another bot.
![image](https://user-images.githubusercontent.com/42511409/232263826-57c3d139-8814-4f1c-87c0-98dffee0e4d2.png)
